.TH ALIZAMS "1" "Jul 2022" "AlizaMS version: 1.8" "User Commands"
.SH NAME
alizams \- Medical Imaging
.SH SYNOPSIS
.B alizams
.RI " [\-nogl] [\-m] [\-s] [files]"
.br
.SH DESCRIPTION
DICOM Viewer.
.SH OPTION
.TP
.BR \-nogl ", "\-\-nogl
Force disable OpenGL module
.TP
.BR \-m ", "\-\-m
File path, only show metadata
.TP
.BR \-s ", "\-\-s
File path, only show metadata, scan series
.PP
.PP
Check the website https://github.com/AlizaMedicalImaging/AlizaMS
