.TH ALIZAMS "1" "Jul 2021" "AlizaMS version: 1.5" "User Commands"
.SH NAME
alizams \- Medical Imaging
.SH SYNOPSIS
.B alizams
.RI " [\-nogl] [\-m] [files]"
.br
.SH DESCRIPTION
DICOM Viewer.
.SH OPTION
.TP
.BR \-nogl ", "\-\-nogl
Force disable OpenGL module
.TP
.BR \-m ", "\-\-m
Only show metadata
.PP
.PP
Check the website https://github.com/AlizaMedicalImaging/AlizaMS
